### ISSUE TITLE
Make `embedToIncludeNewMethods()` a public method to allow mocking

### ISSUE THREAD

**Issue by julia-meier-nordstrom** [googleapis/google-cloud-go-testing#9]
We are using a test mocking framework to unit test our datastore implementation. We were happy to find this (very recently made!) library. However, **it is unusable it it's current form because the `embedToIncludeNewMethods()` is unexported**, which prohibits mocking of the method. If the method name was capitalized (changed to `EmbedToIncludeNewMethods()`) we could directly use this library directly in our testing! (as opposed to copying the code manually into our repo and making this change ourselves). Can we propose this as a PR? Or is there other justification that prohibits exporting this method?

**Comment by jba** [comment]
You should embed the interface in your mock, like so:
```
type MockClient struct {
    dsiface.Client
    // other fields go here
}
```

Now implement the methods you need to mock on `MockClient` (or `*MockClient`).

We want to make sure you do this so that if we add new methods to the `dsiface` interfaces, your code won't break. 

The repo README should probably make this clear, @jadekler.

**Comment by jadekler** [comment]
SG, I'll take a TODO to take a docs pass.

**Comment by noseglid** [comment]
Because the mocks themselves have to embed the interface, it is impossible (almost) to use generated mocks, such as  [gomock](https://github.com/golang/mock).

I've worked around this for now by running `sed` and embedding the interface after i've generated the mocks, but this feels so convoluted.

Would you consider removing/making it exported?
